In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from tqdm import tqdm



pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [2]:
df = pd.read_csv('../data/processed/simulation_2020.csv')

In [3]:
df.head(54)

    year     state_x   dem_perc   gop_perc  ev
0   2020          AK  45.319057  48.875010   3
1   2020          AL  39.770319  53.962899   9
2   2020          AR  45.000000  47.000000   6
3   2020          AZ  47.604275  44.372482  11
4   2020          CA  61.994622  31.799223  55
5   2020          CO  53.497936  39.208129   9
6   2020          CT  51.526992  34.629881   7
7   2020          DC  48.289024  41.536158   3
8   2020          DE  48.289024  41.536158   3
9   2020          FL  48.142045  45.083859  29
10  2020          GA  46.376003  46.838493  16
11  2020          HI  48.289024  41.536158   4
12  2020          IA  45.593964  48.627015   6
13  2020          ID  48.289024  41.536158   4
14  2020          IL  48.289024  41.536158  20
15  2020          IN  39.000000  50.599478  11
16  2020          KS  40.000000  52.000000   6
17  2020          KY  37.626437  55.724388   8
18  2020          LA  48.289024  41.536158   8
19  2020          MA  59.653528  28.705164  11
20  2020          MD  59.100000  35.300000  10
21  2020          ME  52.055556  41.230503   2
22  2020          MI  48.809974  42.253568  16
23  2020          MN  50.268704  42.499306  10
24  2020          MO  44.208234  48.983294  10
25  2020          MS  39.419703  49.597398   6
26  2020          MT  42.447996  50.122931   3
27  2020  Maine CD-1  55.000000  35.000000   1
28  2020  Maine CD-2  45.000000  42.000000   1
29  2020          NC  47.001284  45.522528  15
30  2020          ND  38.000000  56.500000   3
31  2020          NE  51.471579  42.585263   5
32  2020          NH  50.315551  41.376883   4
33  2020          NJ  54.572643  33.759814  14
34  2020          NM  52.423099  39.576901   5
35  2020          NV  49.000000  45.000000   6
36  2020          NY  58.327844  31.525733  29
37  2020          OH  45.597780  46.671106  18
38  2020          OK  34.500000  57.000000   7
39  2020          OR  48.289024  41.536158   7
40  2020          PA  48.436943  43.289196  20
41  2020          RI  48.289024  41.536158   4
42  2020          SC  43.929234  50.457077   9
43  2020          SD  48.289024  41.536158   3
44  2020          TN  39.906250  51.697917  11
45  2020          TX  45.414995  45.983076  38
46  2020          UT  38.729659  46.915486   6
47  2020          VA  51.371093  40.664395  13
48  2020          VT  48.289024  41.536158   3
49  2020          WA  57.679355  35.028300  12
50  2020          WI  47.609725  43.262113  10
51  2020          WV  48.289024  41.536158   5
52  2020          WY  48.289024  41.536158   3

In [4]:
df['other'] = 100-df.dem_perc-df.gop_perc

In [5]:
def get_winner(row):
    
    bootstrap = list(np.random.choice(['D', 'R', 'O'], size = 10, p = [row['dem_perc']/100, row['gop_perc']/100,
                                                                    1-row['dem_perc']/100-row['gop_perc']/100]))
    r = bootstrap.count('R')
    d = bootstrap.count('D')
    if r > d:
        return 0
    else:
        return 1

In [6]:
simulation = {}
for i in tqdm(range(100)):
    df['winner'] = df.apply(lambda x: get_winner(x), axis=1)
    df['votes'] = df['winner']*df['ev']
    simulation[i] = [df.votes.sum(), df.ev.sum() - df.votes.sum()]

100%|██████████| 100/100 [00:02<00:00, 48.14it/s]

In [7]:
df_sim = pd.DataFrame.from_dict(simulation, orient='index', columns = ['D', 'R'])

In [8]:
df_sim.describe()

                D           R
count  100.000000  100.000000
mean   359.170000  178.830000
std     39.990417   39.990417
min    261.000000   55.000000
25%    331.750000  160.000000
50%    360.000000  178.000000
75%    378.000000  206.250000
max    483.000000  277.000000